homepage:
    path:  /
    defaults: { _controller: AfsyFrontBundle:Blog:index }

feed_atom:
    path: /feed.atom
    defaults: { _controller: AfsyFrontBundle:Blog:feed }

blog_home:
    path: /blog
    defaults: { _controller: AfsyFrontBundle:Blog:index }

blog_show:
    path: /blog/{slug}
    defaults: { _controller: AfsyFrontBundle:Blog:show }

blog_preview:
    path: /blog/preview/{slug}
    defaults: { _controller: AfsyFrontBundle:Blog:show, preview: true }

blog_show_tag:
    path: /blog/tag/{name}
    defaults: { _controller: AfsyFrontBundle:Blog:showTag }

avent:
    path: /avent/{year}
    defaults: { _controller: AfsyFrontBundle:Avent:index, year: null }

avent_feed_atom:
    path: /avent/{year}/feed.atom
    defaults: { _controller: AfsyFrontBundle:Avent:feed, _format: xml }

avent_day:
    path: /avent/{year}/{slug}
    defaults: { _controller: AfsyFrontBundle:Avent:day }
